CREATE TABLE jobs (
    id UUID PRIMARY KEY NOT NULL,
    name VARCHAR(255) NOT NULL,
    priority VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

